apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-home
spec:
  selector:
    matchLabels:
      app: myapp-home
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - containerPort: 80
