apiVersion: v1
kind: Service
metadata:
  name: myapp-home-service
spec:
  selector:
    app: myapp-home
  ports:
  - port: 80
    targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: myapp-
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
