apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myworkapp3
    matchExpressions:
      - { key: app, operator: In, values: [myworkapp3] }
  template:
    metadata:
      name: spider4
      labels:
        env: dev
    spec:
      containers:
        - name: spider4
          image: nginx
          env:
          valueFrom: 
            configMapKeyRef:
              name: myvariables
              key: name
          ports:
           - containerPort: 80