---
apiVersion: v1
kind: Pod
metadata:
  name: spider2
  namespace: mywork
  labels:
    env: dev
spec:
  containers:
    - name: spider2
      image: nginx
      ports:
        - containerPort: 80
...
---
