---
apiVersion: v1
kind: Pod
metadata:
  name: spider2
  labels:
    env: dev
spec:
  containers:
    - name: spider2
      image: nginx
      ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
