---
apiVersion: v1
kind: Pod
metadata:
  name: spider2
  labels:
    env: dev
spec:
  containers:
    - name: spider2
      image: nginx
      ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: spider2
spec:
  type: NodePort
  selector:
    app: spider2
  ports:
  - port: 80
    targetPort: 80
