version: "3"
services:
  webserver:
    image: surajbele/batchb9:v1
    ports:
      - 80:80
    environment:
      - department=dev
  backend:
    image: surajbele/batch9:alpine
    ports:
      - 8080:80
    volume:
      - : 
