apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "usr/share/nginx/html"
        name: mypv
  