apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: mybinding
subjects:           #define user details 
- kind: User       #user
  name: spiderman       #user name
  apiGroup: "rbac.authorization.k8s.io"

roleRef:
  kind: Role
  name: pod-reader
  apiGroup: "rbac.authorization.k8s.io"

